"""brief task allocation

Revision ID: d8e5cb615c88
Revises: aa2bf7a082a6
Create Date: 2026-06-29 18:04:19.032980
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd8e5cb615c88'
down_revision: Union[str, None] = 'aa2bf7a082a6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'banner_images', 'banner_image_messages', ['active_message_id'], ['id'], ondelete='SET NULL', use_alter=True)
    op.add_column('briefs', sa.Column('copywriter_id', sa.UUID(), nullable=True))
    op.add_column('briefs', sa.Column('marketing_id', sa.UUID(), nullable=True))
    op.add_column('briefs', sa.Column('product_id', sa.UUID(), nullable=True))
    op.add_column('briefs', sa.Column('designer_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_briefs_copywriter_id'), 'briefs', ['copywriter_id'], unique=False)
    op.create_index(op.f('ix_briefs_designer_id'), 'briefs', ['designer_id'], unique=False)
    op.create_index(op.f('ix_briefs_marketing_id'), 'briefs', ['marketing_id'], unique=False)
    op.create_index(op.f('ix_briefs_product_id'), 'briefs', ['product_id'], unique=False)
    op.create_foreign_key(None, 'briefs', 'users', ['copywriter_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'briefs', 'users', ['product_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'briefs', 'users', ['designer_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'briefs', 'users', ['marketing_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'briefs', type_='foreignkey')
    op.drop_constraint(None, 'briefs', type_='foreignkey')
    op.drop_constraint(None, 'briefs', type_='foreignkey')
    op.drop_constraint(None, 'briefs', type_='foreignkey')
    op.drop_index(op.f('ix_briefs_product_id'), table_name='briefs')
    op.drop_index(op.f('ix_briefs_marketing_id'), table_name='briefs')
    op.drop_index(op.f('ix_briefs_designer_id'), table_name='briefs')
    op.drop_index(op.f('ix_briefs_copywriter_id'), table_name='briefs')
    op.drop_column('briefs', 'designer_id')
    op.drop_column('briefs', 'product_id')
    op.drop_column('briefs', 'marketing_id')
    op.drop_column('briefs', 'copywriter_id')
    op.drop_constraint(None, 'banner_images', type_='foreignkey')
    # ### end Alembic commands ###
