"""initial uuid schema

Revision ID: aa2bf7a082a6
Revises: 
Create Date: 2026-06-26 18:21:37.586737
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aa2bf7a082a6'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=8), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('notifications_seen_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('briefs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('brief_type', sa.String(length=16), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('stage', sa.String(length=24), nullable=False),
    sa.Column('creator_id', sa.UUID(), nullable=False),
    sa.Column('project_name', sa.String(length=255), nullable=True),
    sa.Column('product_name', sa.String(length=255), nullable=True),
    sa.Column('business_unit', sa.String(length=255), nullable=True),
    sa.Column('owner_name', sa.String(length=255), nullable=True),
    sa.Column('brief_date', sa.Date(), nullable=True),
    sa.Column('sm_go_live_timeline', sa.String(length=255), nullable=True),
    sa.Column('sm_one_line_summary', sa.Text(), nullable=True),
    sa.Column('sm_primary_goal', sa.Text(), nullable=True),
    sa.Column('sm_business_kpi', sa.Text(), nullable=True),
    sa.Column('sm_strategic_context', sa.Text(), nullable=True),
    sa.Column('sm_audience_who', sa.Text(), nullable=True),
    sa.Column('sm_audience_segment', sa.Text(), nullable=True),
    sa.Column('sm_audience_exclusions', sa.Text(), nullable=True),
    sa.Column('sm_mandatories_tnc', sa.Text(), nullable=True),
    sa.Column('sm_platforms', sa.Text(), nullable=True),
    sa.Column('sm_dimensions_specs', sa.Text(), nullable=True),
    sa.Column('sm_final_ui_screen', sa.Text(), nullable=True),
    sa.Column('sm_samples_references', sa.Text(), nullable=True),
    sa.Column('lg_project_purpose', sa.Text(), nullable=True),
    sa.Column('lg_business_objective', sa.Text(), nullable=True),
    sa.Column('lg_marketing_objective', sa.Text(), nullable=True),
    sa.Column('lg_communication_objective', sa.Text(), nullable=True),
    sa.Column('lg_effectiveness_metric', sa.Text(), nullable=True),
    sa.Column('lg_ideal_customer', sa.Text(), nullable=True),
    sa.Column('lg_demo_age', sa.String(length=255), nullable=True),
    sa.Column('lg_demo_gender', sa.String(length=255), nullable=True),
    sa.Column('lg_demo_top_cities', sa.String(length=512), nullable=True),
    sa.Column('lg_goals_motivations', sa.Text(), nullable=True),
    sa.Column('lg_category_insight', sa.Text(), nullable=True),
    sa.Column('lg_conservative_target', sa.Text(), nullable=True),
    sa.Column('lg_aspirational_target', sa.Text(), nullable=True),
    sa.Column('lg_product_insight', sa.Text(), nullable=True),
    sa.Column('lg_key_markets', sa.Text(), nullable=True),
    sa.Column('lg_competition', sa.Text(), nullable=True),
    sa.Column('lg_product_features', sa.Text(), nullable=True),
    sa.Column('lg_key_features_deliverables', sa.Text(), nullable=True),
    sa.Column('lg_unique_offerings', sa.Text(), nullable=True),
    sa.Column('lg_think_before', sa.Text(), nullable=True),
    sa.Column('lg_think_after', sa.Text(), nullable=True),
    sa.Column('lg_feel_before', sa.Text(), nullable=True),
    sa.Column('lg_feel_after', sa.Text(), nullable=True),
    sa.Column('lg_do_before', sa.Text(), nullable=True),
    sa.Column('lg_do_after', sa.Text(), nullable=True),
    sa.Column('lg_cultural_sensitivity', sa.Text(), nullable=True),
    sa.Column('lg_languages', sa.Text(), nullable=True),
    sa.Column('lg_other_considerations', sa.Text(), nullable=True),
    sa.Column('lg_deliverables', sa.Text(), nullable=True),
    sa.Column('review_note', sa.Text(), nullable=True),
    sa.Column('reviewer_id', sa.UUID(), nullable=True),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('strategist_id', sa.UUID(), nullable=True),
    sa.Column('channel_mix', sa.Text(), nullable=True),
    sa.Column('budget_inr', sa.Integer(), nullable=True),
    sa.Column('target_audience', sa.Text(), nullable=True),
    sa.Column('creative_prompt', sa.Text(), nullable=True),
    sa.Column('strategy_authorized_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('gate1_strategy', sa.String(length=24), nullable=False),
    sa.Column('gate1_marketing', sa.String(length=24), nullable=False),
    sa.Column('gate1_product', sa.String(length=24), nullable=False),
    sa.Column('gate1_strategy_by_id', sa.UUID(), nullable=True),
    sa.Column('gate1_marketing_by_id', sa.UUID(), nullable=True),
    sa.Column('gate1_product_by_id', sa.UUID(), nullable=True),
    sa.Column('gate1_strategy_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('gate1_marketing_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('gate1_product_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('figma_file_key', sa.String(length=64), nullable=True),
    sa.Column('figma_file_url', sa.String(length=512), nullable=True),
    sa.Column('figma_exported_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['creator_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['gate1_marketing_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['gate1_product_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['gate1_strategy_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['reviewer_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['strategist_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_briefs_creator_id'), 'briefs', ['creator_id'], unique=False)
    op.create_table('brief_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('brief_id', sa.UUID(), nullable=False),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('action', sa.String(length=255), nullable=False),
    sa.Column('actor_id', sa.UUID(), nullable=True),
    sa.Column('actor_name', sa.String(length=255), nullable=False),
    sa.Column('actor_role', sa.String(length=8), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['brief_id'], ['briefs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_brief_events_brief_id'), 'brief_events', ['brief_id'], unique=False)
    op.create_table('creatives',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('brief_id', sa.UUID(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('visual_reference', sa.Text(), nullable=True),
    sa.Column('headline', sa.Text(), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('cta', sa.String(length=120), nullable=False),
    sa.Column('entity_attribution', sa.Text(), nullable=True),
    sa.Column('terms', sa.Text(), nullable=True),
    sa.Column('model_version', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['brief_id'], ['briefs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_creatives_brief_id'), 'creatives', ['brief_id'], unique=False)
    op.create_table('ai_calls',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('operation', sa.String(length=32), nullable=False),
    sa.Column('provider', sa.String(length=32), nullable=False),
    sa.Column('model', sa.String(length=64), nullable=False),
    sa.Column('brief_id', sa.UUID(), nullable=True),
    sa.Column('creative_id', sa.UUID(), nullable=True),
    sa.Column('actor_id', sa.UUID(), nullable=True),
    sa.Column('input_tokens', sa.Integer(), nullable=False),
    sa.Column('output_tokens', sa.Integer(), nullable=False),
    sa.Column('total_tokens', sa.Integer(), nullable=False),
    sa.Column('latency_ms', sa.Integer(), nullable=False),
    sa.Column('cost_inr', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['brief_id'], ['briefs.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['creative_id'], ['creatives.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_calls_brief_id'), 'ai_calls', ['brief_id'], unique=False)
    op.create_index(op.f('ix_ai_calls_created_at'), 'ai_calls', ['created_at'], unique=False)
    op.create_index(op.f('ix_ai_calls_operation'), 'ai_calls', ['operation'], unique=False)
    op.create_table('banner_images',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('creative_id', sa.UUID(), nullable=False),
    sa.Column('brief_id', sa.UUID(), nullable=False),
    sa.Column('prompt', sa.Text(), nullable=False),
    sa.Column('mime_type', sa.String(length=64), nullable=False),
    sa.Column('data', sa.LargeBinary(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('model_version', sa.String(length=64), nullable=False),
    sa.Column('active_message_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['active_message_id'], ['banner_image_messages.id'], ondelete='SET NULL', use_alter=True),
    sa.ForeignKeyConstraint(['brief_id'], ['briefs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['creative_id'], ['creatives.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_banner_images_brief_id'), 'banner_images', ['brief_id'], unique=False)
    op.create_index(op.f('ix_banner_images_creative_id'), 'banner_images', ['creative_id'], unique=True)
    op.create_table('banner_image_messages',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('image_id', sa.UUID(), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('prompt', sa.Text(), nullable=False),
    sa.Column('mime_type', sa.String(length=64), nullable=False),
    sa.Column('data', sa.LargeBinary(), nullable=False),
    sa.Column('model_version', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['image_id'], ['banner_images.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_banner_image_messages_image_id'), 'banner_image_messages', ['image_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_banner_image_messages_image_id'), table_name='banner_image_messages')
    op.drop_table('banner_image_messages')
    op.drop_index(op.f('ix_banner_images_creative_id'), table_name='banner_images')
    op.drop_index(op.f('ix_banner_images_brief_id'), table_name='banner_images')
    op.drop_table('banner_images')
    op.drop_index(op.f('ix_ai_calls_operation'), table_name='ai_calls')
    op.drop_index(op.f('ix_ai_calls_created_at'), table_name='ai_calls')
    op.drop_index(op.f('ix_ai_calls_brief_id'), table_name='ai_calls')
    op.drop_table('ai_calls')
    op.drop_index(op.f('ix_creatives_brief_id'), table_name='creatives')
    op.drop_table('creatives')
    op.drop_index(op.f('ix_brief_events_brief_id'), table_name='brief_events')
    op.drop_table('brief_events')
    op.drop_index(op.f('ix_briefs_creator_id'), table_name='briefs')
    op.drop_table('briefs')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
