{{- if .Values.sync.secrets.enabled | default false }}
{{- $secrets := .Values.sync.secrets.secrets }}
{{- $project_id := .Values.sync.secrets.project_id }}
{{- if gt (len $secrets) 0 }}
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: secret-sync-{{ include "gf.fullname" . }}
  namespace: {{ .Release.Namespace }}
spec:
  provider: gcp
  parameters:
    secrets: |
      {{- range $secrets }}
      - resourceName: "projects/{{ $project_id }}/secrets/{{ . }}/versions/latest"
        fileName: "{{ . }}"
      {{- end }}
  secretObjects:
    {{- range $secrets }}
    - secretName: csi-secret-{{ . | replace "_" "-" | lower }}
      type: Opaque
      data:
        - key: value
          objectName: "{{ . }}"
    {{- end }}
{{- end }}
{{- end }}
