{{- if and .Values.virtualservice .Values.virtualservice.enabled }}
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ include "gf.fullname" . }}
  labels:
    {{- include "gf.labels" . | nindent 4 }}
spec:
  hosts:
    - '{{ .Values.virtualservice.host }}'
  gateways:
    - {{ .Values.virtualservice.gateway }}
  http:
    - match:
        - uri:
            prefix: {{ .Values.virtualservice.apiPrefix | default "/api" }}
      headers:
        response:
          remove:
          - server
      route:
        - destination:
            host: {{ include "gf.fullname" . }}-backend
            port:
              number: {{ .Values.virtualservice.backendPort | default 8000 }}
      retries:
        attempts: 3
        perTryTimeout: {{ .Values.virtualservice.perTryTimeout | default "120s" }}
        retryOn: connect-failure,refused-stream,reset,504
      timeout: {{ .Values.virtualservice.timeout | default "600s" }}
    - match:
        - uri:
            prefix: {{ .Values.virtualservice.prefix | default "/" }}
      headers:
        response:
          remove:
          - server
      route:
        - destination:
            host: {{ include "gf.fullname" . }}-frontend
            port:
              number: {{ .Values.virtualservice.frontendPort | default 80 }}
      timeout: {{ .Values.virtualservice.timeout | default "600s" }}
{{- end }}
