"""initial schema

Revision ID: 21cdf93c4e35
Revises: 
Create Date: 2026-06-12 05:43:07.195884+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '21cdf93c4e35'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('knowledge_base_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('topic', sa.String(length=256), nullable=False),
    sa.Column('keywords', sa.JSON(), nullable=False),
    sa.Column('answer', sa.Text(), nullable=False),
    sa.Column('citations', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_knowledge_base_entries_topic'), 'knowledge_base_entries', ['topic'], unique=False)
    op.create_table('playbook_clauses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('clause_type', sa.String(length=64), nullable=False),
    sa.Column('contract_type', sa.String(length=32), nullable=False),
    sa.Column('standard_position', sa.Text(), nullable=False),
    sa.Column('risk_keywords', sa.JSON(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_playbook_clauses_clause_type'), 'playbook_clauses', ['clause_type'], unique=False)
    op.create_table('regulatory_sources',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('regulator', sa.String(length=64), nullable=False),
    sa.Column('reference', sa.String(length=256), nullable=False),
    sa.Column('title', sa.String(length=512), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('tags', sa.JSON(), nullable=False),
    sa.Column('published_on', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_regulatory_sources_regulator'), 'regulatory_sources', ['regulator'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=32), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('role', sa.String(length=32), nullable=False),
    sa.Column('action_type', sa.String(length=64), nullable=False),
    sa.Column('module', sa.String(length=64), nullable=False),
    sa.Column('input_summary', sa.Text(), nullable=True),
    sa.Column('ai_output_summary', sa.Text(), nullable=True),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('human_decision', sa.String(length=32), nullable=True),
    sa.Column('model_version', sa.String(length=64), nullable=True),
    sa.Column('ip_address', sa.String(length=64), nullable=True),
    sa.Column('session_id', sa.String(length=128), nullable=True),
    sa.Column('target_id', sa.Integer(), nullable=True),
    sa.Column('extra', sa.JSON(), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_action_type'), 'audit_logs', ['action_type'], unique=False)
    op.create_index(op.f('ix_audit_logs_module'), 'audit_logs', ['module'], unique=False)
    op.create_index(op.f('ix_audit_logs_timestamp'), 'audit_logs', ['timestamp'], unique=False)
    op.create_index(op.f('ix_audit_logs_user_id'), 'audit_logs', ['user_id'], unique=False)
    op.create_table('contract_templates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('contract_type', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('template_text', sa.Text(), nullable=False),
    sa.Column('storage_key', sa.String(length=512), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('contracts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=512), nullable=False),
    sa.Column('contract_type', sa.String(length=64), nullable=False),
    sa.Column('raw_text', sa.Text(), nullable=False),
    sa.Column('risk_score', sa.Float(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('model_version', sa.String(length=64), nullable=True),
    sa.Column('uploaded_by_id', sa.Integer(), nullable=False),
    sa.Column('reviewed_by_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['reviewed_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['uploaded_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('feature_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=512), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('request_type', sa.String(length=32), nullable=False),
    sa.Column('priority', sa.String(length=4), nullable=False),
    sa.Column('priority_score', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('repository', sa.String(length=256), nullable=True),
    sa.Column('github_issue_number', sa.Integer(), nullable=True),
    sa.Column('github_issue_url', sa.String(length=1024), nullable=True),
    sa.Column('branch_name', sa.String(length=256), nullable=True),
    sa.Column('pr_number', sa.Integer(), nullable=True),
    sa.Column('pr_url', sa.String(length=1024), nullable=True),
    sa.Column('deployment_url', sa.String(length=1024), nullable=True),
    sa.Column('plan', sa.JSON(), nullable=True),
    sa.Column('files_touched', sa.JSON(), nullable=True),
    sa.Column('loc_estimate', sa.Integer(), nullable=True),
    sa.Column('diff_summary', sa.Text(), nullable=True),
    sa.Column('agent_log', sa.JSON(), nullable=False),
    sa.Column('model_version', sa.String(length=64), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=False),
    sa.Column('approved_by_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('state_changed_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('pr_opened_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('merged_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deployed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['approved_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('gmail_credentials',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=256), nullable=False),
    sa.Column('access_token', sa.Text(), nullable=False),
    sa.Column('refresh_token', sa.Text(), nullable=True),
    sa.Column('token_expiry', sa.DateTime(timezone=True), nullable=True),
    sa.Column('label_id', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('legal_bot_queries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('question', sa.Text(), nullable=False),
    sa.Column('ai_answer', sa.Text(), nullable=True),
    sa.Column('citations', sa.JSON(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('tier', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('legal_override', sa.Text(), nullable=True),
    sa.Column('overridden_by_id', sa.Integer(), nullable=True),
    sa.Column('model_version', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['overridden_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_legal_bot_queries_user_id'), 'legal_bot_queries', ['user_id'], unique=False)
    op.create_table('regulatory_updates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=512), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('full_text', sa.Text(), nullable=True),
    sa.Column('url', sa.String(length=1024), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=False),
    sa.Column('relevance_score', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ingested_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('triaged_by_id', sa.Integer(), nullable=True),
    sa.Column('impact_note', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['triaged_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_regulatory_updates_source'), 'regulatory_updates', ['source'], unique=False)
    op.create_table('research_notes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('query', sa.Text(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('applicable_regulations', sa.JSON(), nullable=False),
    sa.Column('key_provisions', sa.JSON(), nullable=False),
    sa.Column('implications', sa.Text(), nullable=False),
    sa.Column('recommended_next_steps', sa.JSON(), nullable=False),
    sa.Column('citations', sa.JSON(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('reviewer_notes', sa.Text(), nullable=True),
    sa.Column('model_version', sa.String(length=64), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=False),
    sa.Column('finalized_by_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('finalized_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['finalized_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tasks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=512), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('source_module', sa.String(length=32), nullable=True),
    sa.Column('source_ref_id', sa.Integer(), nullable=True),
    sa.Column('email_sender', sa.String(length=256), nullable=True),
    sa.Column('email_subject', sa.String(length=512), nullable=True),
    sa.Column('email_body', sa.Text(), nullable=True),
    sa.Column('priority', sa.String(length=4), nullable=False),
    sa.Column('priority_score', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('due_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('estimated_minutes', sa.Integer(), nullable=True),
    sa.Column('snoozed_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=False),
    sa.Column('assigned_to_id', sa.Integer(), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=False),
    sa.Column('ai_confidence', sa.Float(), nullable=True),
    sa.Column('ai_rationale', sa.Text(), nullable=True),
    sa.Column('model_version', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['assigned_to_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('contract_clauses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('contract_id', sa.Integer(), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('heading', sa.String(length=256), nullable=True),
    sa.Column('clause_text', sa.Text(), nullable=False),
    sa.Column('risk_flag', sa.String(length=16), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('ai_rationale', sa.Text(), nullable=True),
    sa.Column('ai_suggestion', sa.Text(), nullable=True),
    sa.Column('decision', sa.String(length=16), nullable=False),
    sa.Column('reviewer_edit', sa.Text(), nullable=True),
    sa.Column('reviewer_comment', sa.Text(), nullable=True),
    sa.Column('references', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['contract_id'], ['contracts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('msa_trackers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vendor_name', sa.String(length=256), nullable=False),
    sa.Column('vendor_email', sa.String(length=256), nullable=False),
    sa.Column('contract_type', sa.String(length=32), nullable=False),
    sa.Column('deal_reference', sa.String(length=128), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('risk_score', sa.Float(), nullable=True),
    sa.Column('current_version', sa.Integer(), nullable=False),
    sa.Column('original_text', sa.Text(), nullable=True),
    sa.Column('redlined_text', sa.Text(), nullable=True),
    sa.Column('ai_suggestions', sa.JSON(), nullable=True),
    sa.Column('template_id', sa.Integer(), nullable=True),
    sa.Column('canonical_version_id', sa.Integer(), nullable=True),
    sa.Column('executed_version_id', sa.Integer(), nullable=True),
    sa.Column('gmail_thread_id', sa.String(length=128), nullable=True),
    sa.Column('assigned_to_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['assigned_to_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['canonical_version_id'], ['msa_document_versions.id'], name='fk_msa_canonical_version', use_alter=True),
    sa.ForeignKeyConstraint(['executed_version_id'], ['msa_document_versions.id'], name='fk_msa_executed_version', use_alter=True),
    sa.ForeignKeyConstraint(['template_id'], ['contract_templates.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('msa_document_versions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tracker_id', sa.Integer(), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('extracted_text', sa.Text(), nullable=False),
    sa.Column('storage_key', sa.String(length=512), nullable=True),
    sa.Column('filename', sa.String(length=512), nullable=True),
    sa.Column('mime_type', sa.String(length=128), nullable=True),
    sa.Column('sha256', sa.String(length=64), nullable=True),
    sa.Column('parent_version_id', sa.Integer(), nullable=True),
    sa.Column('comparison_id', sa.Integer(), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('gmail_message_id', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['comparison_id'], ['document_comparisons.id'], name='fk_msa_version_comparison', use_alter=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['parent_version_id'], ['msa_document_versions.id'], ),
    sa.ForeignKeyConstraint(['tracker_id'], ['msa_trackers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_msa_document_versions_tracker_id'), 'msa_document_versions', ['tracker_id'], unique=False)
    op.create_table('document_comparisons',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(length=256), nullable=False),
    sa.Column('v1_filename', sa.String(length=512), nullable=False),
    sa.Column('v2_filename', sa.String(length=512), nullable=False),
    sa.Column('v1_text', sa.Text(), nullable=False),
    sa.Column('v2_text', sa.Text(), nullable=False),
    sa.Column('diff_blocks', sa.JSON(), nullable=False),
    sa.Column('risk_commentary', sa.JSON(), nullable=False),
    sa.Column('summary_report', sa.Text(), nullable=False),
    sa.Column('llm_narrative', sa.JSON(), nullable=True),
    sa.Column('tracker_id', sa.Integer(), nullable=True),
    sa.Column('from_version_id', sa.Integer(), nullable=True),
    sa.Column('to_version_id', sa.Integer(), nullable=True),
    sa.Column('model_version', sa.String(length=64), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['from_version_id'], ['msa_document_versions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['to_version_id'], ['msa_document_versions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tracker_id'], ['msa_trackers.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_document_comparisons_tracker_id'), 'document_comparisons', ['tracker_id'], unique=False)
    op.create_table('msa_emails',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tracker_id', sa.Integer(), nullable=False),
    sa.Column('version_id', sa.Integer(), nullable=True),
    sa.Column('direction', sa.String(length=8), nullable=False),
    sa.Column('from_addr', sa.String(length=256), nullable=False),
    sa.Column('to_addr', sa.String(length=256), nullable=False),
    sa.Column('subject', sa.String(length=512), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('attachment_name', sa.String(length=512), nullable=True),
    sa.Column('attachment_storage_key', sa.String(length=512), nullable=True),
    sa.Column('gmail_message_id', sa.String(length=128), nullable=True),
    sa.Column('sent_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('sent_by_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['sent_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['tracker_id'], ['msa_trackers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['version_id'], ['msa_document_versions.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_msa_emails_tracker_id'), 'msa_emails', ['tracker_id'], unique=False)
    op.create_table('negotiation_change_tasks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tracker_id', sa.Integer(), nullable=False),
    sa.Column('version_id', sa.Integer(), nullable=True),
    sa.Column('comparison_id', sa.Integer(), nullable=True),
    sa.Column('diff_index', sa.Integer(), nullable=True),
    sa.Column('clause_ref', sa.String(length=256), nullable=True),
    sa.Column('severity', sa.String(length=16), nullable=False),
    sa.Column('title', sa.String(length=512), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('suggested_action', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('assigned_to_id', sa.Integer(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['assigned_to_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['comparison_id'], ['document_comparisons.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tracker_id'], ['msa_trackers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['version_id'], ['msa_document_versions.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_negotiation_change_tasks_tracker_id'), 'negotiation_change_tasks', ['tracker_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_negotiation_change_tasks_tracker_id'), table_name='negotiation_change_tasks')
    op.drop_table('negotiation_change_tasks')
    op.drop_index(op.f('ix_msa_emails_tracker_id'), table_name='msa_emails')
    op.drop_table('msa_emails')
    op.drop_index(op.f('ix_document_comparisons_tracker_id'), table_name='document_comparisons')
    op.drop_table('document_comparisons')
    op.drop_index(op.f('ix_msa_document_versions_tracker_id'), table_name='msa_document_versions')
    op.drop_table('msa_document_versions')
    op.drop_table('msa_trackers')
    op.drop_table('contract_clauses')
    op.drop_table('tasks')
    op.drop_table('research_notes')
    op.drop_index(op.f('ix_regulatory_updates_source'), table_name='regulatory_updates')
    op.drop_table('regulatory_updates')
    op.drop_index(op.f('ix_legal_bot_queries_user_id'), table_name='legal_bot_queries')
    op.drop_table('legal_bot_queries')
    op.drop_table('gmail_credentials')
    op.drop_table('feature_requests')
    op.drop_table('contracts')
    op.drop_table('contract_templates')
    op.drop_index(op.f('ix_audit_logs_user_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_timestamp'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_module'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_action_type'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_regulatory_sources_regulator'), table_name='regulatory_sources')
    op.drop_table('regulatory_sources')
    op.drop_index(op.f('ix_playbook_clauses_clause_type'), table_name='playbook_clauses')
    op.drop_table('playbook_clauses')
    op.drop_index(op.f('ix_knowledge_base_entries_topic'), table_name='knowledge_base_entries')
    op.drop_table('knowledge_base_entries')
    # ### end Alembic commands ###
