apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "genaiforge.fullname" . }}-backend
  labels:
    {{- include "genaiforge.labels" . | nindent 4 }}
    app.kubernetes.io/component: backend
spec:
  {{- if not .Values.backend.autoscaling.enabled }}
  replicas: {{ .Values.backend.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "genaiforge.backend.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "genaiforge.backend.selectorLabels" . | nindent 8 }}
    spec:
      automountServiceAccountToken: false
      serviceAccountName: {{ include "genaiforge.serviceAccountName" . }}
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: backend
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.backend.image.repository }}:{{ .Values.backend.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.backend.image.pullPolicy }}
          env:
            {{- range .Values.podEnv }}
            - name: {{ .name }}
              {{- if .valueFrom }}
              valueFrom:
                secretKeyRef:
                  name: {{ .valueFrom.secretKeyRef.name }}
                  key: {{ .valueFrom.secretKeyRef.key }}
              {{- else }}
              value: {{ .value | quote }}
              {{- end }}
            {{- end }}
          ports:
            - name: http
              containerPort: {{ .Values.backend.service.port }}
              protocol: TCP
          resources:
            {{- toYaml .Values.backend.resources | nindent 12 }}

        {{- if .Values.cloudsqlproxy.enabled }}
        - name: cloud-sql-proxy
          image: "{{ .Values.cloudsqlproxy.image }}"
          args:
            {{- range .Values.cloudsqlproxy.args }}
            - {{ . | quote }}
            {{- end }}
            - "--port={{ .Values.cloudsqlproxy.port }}"
            - "{{ .Values.cloudsqlproxy.instanceConnectionName }}"
          securityContext:
            runAsNonRoot: true
          resources:
            {{- toYaml .Values.cloudsqlproxy.resources | nindent 12 }}
        {{- end }}

      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
